framework:
  assets:
    packages:
      backend:
        json_manifest_path: '%kernel.project_dir%/public/backend/manifest.json'
      frontend:
        json_manifest_path: '%kernel.project_dir%/public/frontend/manifest.json'